version: '3'
services:
  nodes-app:
    build:
      context: .
      dockerfile: Dockerfile.txt
    ports:
      - 8081:80    
    volumes:
      - my-vol:/usr/local/apache2/htdocs
volumes:
  my-vol:
    external: true